const portfolioItems: PortfolioItem[] = [
  {
    title: "Data labeller",
    description: "A data labelling tool for machine learning projects",
    type: ["web", "app"],
    image: "https://picsum.photos/200/300",
    url: "https://data-labeller.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/data-labeller",
    liveDemoUrl: "https://data-labeller.vercel.app/",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    duration: "4 months",
    dateCompleted: "June 2023",
    role: "Full-Stack Developer",
  },
  {
    title: "Data Collection Tool",
    description: "A data collection tool for machine learning projects",
    type: ["mobile", "app"],
    image: "https://picsum.photos/200/200",
    url: "https://data-collection-tool.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/data-collection-tool",
    liveDemoUrl: "https://data-collection-tool.vercel.app/",
    techStack: ["React Native", "Firebase"],
    duration: "3 months",
    dateCompleted: "March 2023",
    role: "Mobile Developer",
  },

  {
    title: "Admin Dashboard - FastHTML",
    description: "An admin dashboard for managing users",
    type: ["web", "app"],
    image: "/images/portfolio/admin-dashboard.png",
    url: "https://fast-ht-ml-panel.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/admin-dashboard",
    liveDemoUrl: "https://fast-ht-ml-panel.vercel.app/",
    techStack: ["React", "Redux", "Material UI"],
    duration: "2 months",
    dateCompleted: "June 2023",
    role: "Frontend Developer",
  },
  {
    title: "Personal React Library",
    description: "A collection of React components I use in my projects",
    type: ["web", "collection"],
    image: "/images/portfolio/react-library.png",
    url: "https://react-component-collection-delta.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/react-library",
    liveDemoUrl: "https://react-component-collection-delta.vercel.app/",
    techStack: ["React", "TypeScript"],
    duration: "Ongoing",
    dateCompleted: "N/A",
    role: "Frontend Developer",
  },
  {
    title: "Obsidian Plugin",
    description: "A plugin for the Obsidian note-taking app",
    type: ["desktop", "collection"],
    image: "/images/portfolio/obsidian-plugin.png",
    url: "#", // Not yet deployed
    sourceCodeUrl: "https://github.com/your-username/obsidian-plugin",
    liveDemoUrl: "#", // Not yet available
    techStack: ["JavaScript", "Obsidian API"],
    duration: "1 month",
    dateCompleted: "August 2023",
    role: "Plugin Developer",
  },
  {
    title: "Timeline 7",
    description: "A novel I wrote",
    type: ["media"],
    image: "/images/portfolio/timeline-7.png",
    url: "https://www.amazon.com/dp/B09DQ9QX2F",
    techStack: ["Writing", "Publishing"],
    duration: "1 year",
    dateCompleted: "October 2022",
    role: "Author",
  },
  {
    title: "Greenhorn",
    description: "Animated TV series",
    type: ["media"],
    image: "/images/portfolio/greenhorn.png",
    url: "https://www.youtube.com/watch?v=2X0H4Yb3XpM",
    techStack: ["Animation", "Storyboarding"],
    duration: "2 years",
    dateCompleted: "July 2023",
    role: "Animator",
  },
  {
    title: "Mind a Drift",
    description: "A short story I wrote",
    type: ["media"],
    image: "/images/portfolio/short-story.png",
    url: "https://www.amazon.com/dp/B09DQ9QX2F",
    techStack: ["Writing", "Publishing"],
    duration: "3 months",
    dateCompleted: "November 2021",
    role: "Author",
  },
];

export default portfolioItems;