const portfolioItems: PortfolioItem[] = [
  {
    title: "Data labeller",
    description: "A data labelling tool for machine learning projects",
    type: ["web", "app"],
    image: "https://picsum.photos/200/300",
    url: "https://data-labeller.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/data-labeller",
    liveDemoUrl: "https://data-labeller.vercel.app/",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    duration: "4 months",
    dateCompleted: "June 2023",
    role: "Full-Stack Developer",
  },
  {
    title: "Previous Portfolio",
    description: "My old portfolio site that was more frontend focused",
    type: ["web", "app"],
    image: "/images/time.jpeg",
    url: "https://www.zsdynamics.com",
    sourceCodeUrl: "https://github.com/your-username/previous-portfolio",
    liveDemoUrl: "https://www.zsdynamics.com",
    techStack: ["HTML", "CSS", "JavaScript"],
    duration: "2 months",
    dateCompleted: "February 2022",
    role: "Frontend Developer",
  },
  {
    title: "Data Collection Tool",
    description: "A data collection tool for machine learning projects",
    type: ["mobile", "app"],
    image: "https://picsum.photos/200/200",
    url: "https://data-collection-tool.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/data-collection-tool",
    liveDemoUrl: "https://data-collection-tool.vercel.app/",
    techStack: ["React Native", "Firebase"],
    duration: "3 months",
    dateCompleted: "March 2023",
    role: "Mobile Developer",
  },
  {
    title: "PMA",
    description: "A project management application",
    type: ["desktop", "app"],
    image: "/images/portfolio/pma.png",
    url: "#", // Not yet deployed
    sourceCodeUrl: "https://github.com/your-username/pma",
    liveDemoUrl: "#", // Not yet available
    techStack: ["Electron", "React", "SQLite"],
    duration: "5 months",
    dateCompleted: "July 2023",
    role: "Full-Stack Developer",
  },
  {
    title: "Xylo-clone",
    description: "A clone of the Xylo app",
    type: ["web", "app"],
    image: "/images/portfolio/xylo-clone.png",
    url: "https://xylo-clone.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/xylo-clone",
    liveDemoUrl: "https://xylo-clone.vercel.app/",
    techStack: ["Next.js", "Tailwind CSS"],
    duration: "2 months",
    dateCompleted: "April 2023",
    role: "Frontend Developer",
  },
  {
    title: "ClassChat Clone",
    description: "A clone of the ClassChat app",
    type: ["web", "app"],
    image: "/images/portfolio/classchat-clone.png",
    url: "https://class-chat-clone.vercel.app/class",
    sourceCodeUrl: "https://github.com/your-username/classchat-clone",
    liveDemoUrl: "https://class-chat-clone.vercel.app/class",
    techStack: ["React", "Firebase", "Tailwind CSS"],
    duration: "3 months",
    dateCompleted: "May 2023",
    role: "Full-Stack Developer",
  },
  {
    title: "Admin Dashboard - FastHTML",
    description: "An admin dashboard for managing users",
    type: ["web", "app"],
    image: "/images/portfolio/admin-dashboard.png",
    url: "https://fast-ht-ml-panel.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/admin-dashboard",
    liveDemoUrl: "https://fast-ht-ml-panel.vercel.app/",
    techStack: ["React", "Redux", "Material UI"],
    duration: "2 months",
    dateCompleted: "June 2023",
    role: "Frontend Developer",
  },
  {
    title: "Personal React Library",
    description: "A collection of React components I use in my projects",
    type: ["web", "collection"],
    image: "/images/portfolio/react-library.png",
    url: "https://react-component-collection-delta.vercel.app/",
    sourceCodeUrl: "https://github.com/your-username/react-library",
    liveDemoUrl: "https://react-component-collection-delta.vercel.app/",
    techStack: ["React", "TypeScript"],
    duration: "Ongoing",
    dateCompleted: "N/A",
    role: "Frontend Developer",
  },
  {
    title: "Obsidian Plugin",
    description: "A plugin for the Obsidian note-taking app",
    type: ["desktop", "collection"],
    image: "/images/portfolio/obsidian-plugin.png",
    url: "#", // Not yet deployed
    sourceCodeUrl: "https://github.com/your-username/obsidian-plugin",
    liveDemoUrl: "#", // Not yet available
    techStack: ["JavaScript", "Obsidian API"],
    duration: "1 month",
    dateCompleted: "August 2023",
    role: "Plugin Developer",
  },
  {
    title: "Custom NPM",
    description: "A collection of custom NPM packages",
    type: ["web", "collection"],
    image: "/images/portfolio/custom-npm.png",
    url: "https://www.npmjs.com/~zsd",
    sourceCodeUrl: "https://github.com/your-username/custom-npm",
    liveDemoUrl: "https://www.npmjs.com/~zsd",
    techStack: ["Node.js", "TypeScript"],
    duration: "Ongoing",
    dateCompleted: "N/A",
    role: "Package Developer",
  },
  {
    title: "VSC Extension",
    description: "A collection of custom Visual Studio Code extensions",
    type: ["desktop", "collection"],
    image: "/images/portfolio/vsc-extension.png",
    url: "https://marketplace.visualstudio.com/publishers/zsd",
    sourceCodeUrl: "https://github.com/your-username/vsc-extension",
    liveDemoUrl: "https://marketplace.visualstudio.com/publishers/zsd",
    techStack: ["TypeScript", "Visual Studio Code API"],
    duration: "3 months",
    dateCompleted: "September 2023",
    role: "Extension Developer",
  },
  {
    title: "Timeline 7",
    description: "A novel I wrote",
    type: ["media"],
    image: "/images/portfolio/timeline-7.png",
    url: "https://www.amazon.com/dp/B09DQ9QX2F",
    techStack: ["Writing", "Publishing"],
    duration: "1 year",
    dateCompleted: "October 2022",
    role: "Author",
  },
  {
    title: "Greenhorn",
    description: "Animated TV series",
    type: ["media"],
    image: "/images/portfolio/greenhorn.png",
    url: "https://www.youtube.com/watch?v=2X0H4Yb3XpM",
    techStack: ["Animation", "Storyboarding"],
    duration: "2 years",
    dateCompleted: "July 2023",
    role: "Animator",
  },
  {
    title: "3D models",
    description: "3D models I created",
    type: ["media"],
    image: "/images/portfolio/3d-models.png",
    url: "https://sketchfab.com/zsd",
    techStack: ["Blender", "3D Modeling"],
    duration: "Ongoing",
    dateCompleted: "N/A",
    role: "3D Artist",
  },
  {
    title: "Short story",
    description: "A short story I wrote",
    type: ["media"],
    image: "/images/portfolio/short-story.png",
    url: "https://www.amazon.com/dp/B09DQ9QX2F",
    techStack: ["Writing", "Publishing"],
    duration: "3 months",
    dateCompleted: "November 2021",
    role: "Author",
  },
];

export default portfolioItems;